const WP = {
  archery: [
    { strike: 1, parry: 1, rof: 2 },
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1, rof: 1 },
    { strike: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1 },
  ],
  axe: [
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
  ],
  blunt: [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { throw: 1 },
  ],
  chain: [
    { strike: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
  ],
  forked: [
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    { throw: 1 },
    { strike: 1, entangle: 1 },
    { parry: 1 },
    {},
    { strike: 1, entangle: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { throw: 1 },
  ],
  knife: [
    { parry: 1, throw: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1 },
    { throw: 1 },
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    {},
  ],
  "grappling hook": [
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    {},
  ],
  "pole arm": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
  ],
  rope: [
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    { strike: 1 },
  ],
  shield: [
    { parry: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
  ],
  spear: [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    {},
  ],
  staff: [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
  ],
  sword: [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
  ],
  targeting: [
    { strike: 1 },
    { damage: 1 },
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    { damage: 1 },
    {},
    { strike: 1 },
    {},
    {},
    {},
    {},
    {},
  ],
  whip: [
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    { damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    { damage: 1 },
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
  ],
  handguns: [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  rifles: [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "energy heavy": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "energy pistol": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
  ],
  "energy rifle": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  heavy: [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  speargun: [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
  ],
  shotgun: [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  submachinegun: [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, burst: 1 },
  ],
  flamethrower: [
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1, burst: 1 },
  ],
};

const WP_KEYS = {
  wp: [
    "skill",
    "skill_level",
    "strike",
    "parry",
    "disarm",
    "rof",
    "throw",
    "entangle",
  ],
  wpmodern: ["skill", "skill_level", "strike_range_single", "disarm", "burst"],
};

const COMBAT_KEYS = [
  "selection_id",
  "skill",
  "skill_level",
  "attacks",
  "initiative",
  "strike",
  "parry",
  "dodge",
  "throw",
  "disarm",
  "entangle",
  "pull",
  "roll",
  "damage",
  "dodge_flight",
  "dodge_auto",
  "dodge_teleport",
  "dodge_motion",
  "strike_range",
  "strike_range_single",
  "burst",
  "critical",
];
const SAVE_KEYS_ATTRIBUTE_BONUSES = {
  me_bonus: ["psionics", "insanity"],
  pe_bonus: ["magic", "poison", "disease", "torture", "fatigue", "toxins"],
  pe_coma_bonus: ["comadeath"],
  none: ["horrorfactor", "mindcontrol", "illusions", "possession"],
};
const SAVE_KEYS = Object.values(SAVE_KEYS_ATTRIBUTE_BONUSES).reduce(
  (acc, cur) => acc.concat(),
  []
);
const COMBAT_SAVE_KEYS = COMBAT_KEYS.concat(SAVE_KEYS);
